General improvements in string handling from config check (Fixes #4)
custom-components/config_check pull request #5
Opened 2020-12-20 21:10 UTC by pplucky

General improvements in string handling from config check:
- Use regular expression to exclude colorlog install attempts which sometimes appear
- Remove escape characters (not needed and causing issues in service call)
- Remove everything before string 'Failed config' (it is repeated anyway after)
- Make sure text is not removed if it contains string 'Invalid config'
- Remove '(See' (lost after split by ?)

2021-05-31 08:17 UTC, ludeeus requested changes

2021-05-31 08:17 UTC, ludeeus commented on custom_components/config_check/__init__.py
> +import re, logging
```suggestion
import re
import logging

```

2021-05-31 08:17 UTC, ludeeus commented on custom_components/config_check/__init__.py
> +    """Remove HA colorlog install attempt, regardless of version """
```suggestion
    # Remove HA colorlog install attempt, regardless of version

```

`"""` are used for docstring/multiline comments, `# ` are used for single line

2021-05-31 08:17 UTC, ludeeus commented on custom_components/config_check/__init__.py
> +    """Remove escape characters /"""
```suggestion
    # Remove escape characters /

```

2021-05-31 08:17 UTC, ludeeus commented on custom_components/config_check/__init__.py
> +    """Remove everything before Failed config."""
```suggestion
    # Remove everything before Failed config

```

2021-05-31 08:17 UTC, ludeeus commented on custom_components/config_check/__init__.py
> +    """Remove '(See' at end of string."""
```suggestion
    # Remove '(See' at end of string

```

2021-06-01 22:08 UTC, ludeeus commented
<https://github.com/custom-components/config_check/blob/master/custom_components/config_check/manifest.json#L2> bump this to 0.1.1 as well

2021-06-01 22:14 UTC, pplucky commented
> https://github.com/custom-components/config_check/blob/master/custom_components/config_check/manifest.json#L2 bump this to 0.1.1 as well

Done, thanks.

2021-06-01 22:19 UTC, ludeeus commented
You added a duplicate of the file in the root, that's not right

2021-06-01 22:25 UTC, pplucky commented
> You added a duplicate of the file in the root, that's not right

Sorry, not very used to do this, but still wanting to contribute. Should be OK now.

2021-06-01 22:25 UTC, ludeeus approved these changes

2021-06-01 22:26 UTC, merged